### ISSUE TITLE
Report designer fixed screen width

### ISSUE THREAD

**Issue by MBrekhof** [Terricks/XAFBootstrap#1]
The web based report designer opens fine but the screen is a fixed size (too small)
![designer](https://cloud.githubusercontent.com/assets/13586354/9005234/bbeca530-377c-11e5-8323-91d47f7fd1b1.PNG)

**Comment by Terricks** [comment]
Added support for
maximizing popup window to fullscreen mode.

**Comment by MBrekhof** [comment]
works great, thanks
