### ISSUE TITLE
Focus problem

### ISSUE THREAD

**Issue by volkanalkilic** [Terricks/XAFBootstrap#10]
i am using following code for set focus to editors when the enter key is pressed;
This code works fine on new XAF mobile theme, but not works on XAFBootstrap.

Code:

```
    private void CurrentRequestWindow_PagePreRender(object sender, EventArgs e)
    {
        var window = (WebWindow)sender;
        var script = IsSuitableView() ? @"window.onkeydown = function(e) {
                                              var key = e.keyCode ? e.keyCode : e.which;
                                              if (key == 13) { 

                                                  RaiseXafCallback(globalCallbackControl, 'T171941', 'ENTER', '', false);
                                              }
                                           };" : "window.onkeydown=undefined;";
        window.RegisterStartupScript(GetType().FullName, script);
    }
    public void ProcessAction(string parameter)
    {
        if (IsSuitableView() && (Frame != null))
        {
            switch (parameter)
            {
                case "ENTER":
                    if (Convert.ToInt32(MiktarEdit.PropertyValue) > 0)
                    {
                        BakodEdit.Editor.Focus();
                    }
                    else
                    {
                        MiktarEdit.Editor.Focus();
                    }
                    break;
            }
        }
    }
```

**Comment by Terricks** [comment]
Focus logic is not supported for now.

**Comment by volkanalkilic** [comment]
Do you have any plans to support focus logic?

**Comment by Terricks** [comment]
I think yes, it's possible, so I'll mark this issue as enhancement

**Comment by volkanalkilic** [comment]
this feuture will be useful when ready, but I need a quick solution.
is there any way to catch Enter key and set fous to other editor? can you give some example?

**Comment by Terricks** [comment]
For your task you can use WebWindow.CurrentRequestWindow.RegisterStartupScript in your controller and register logic you need to do with javascript.

For example, this script sets focus to input element with specified placeholder:

<pre>
protected override void OnViewControlsCreated()
{
     base.OnViewControlsCreated();
     WebWindow.CurrentRequestWindow.RegisterStartupScript("SetFocusToElement", "$('[placeholder=Имя]').focus();");
}
</pre>

**Comment by Terricks** [comment]
Enhanced in release 15.2
