### ISSUE TITLE
Log on Null Reference Exception.

### ISSUE THREAD

**Issue by Stwart** [Terricks/XAFBootstrap#11]
The exception happens just after the log on button is pressed

The error occurred:
    Type:       NullReferenceException
    Message:    Referência de objeto não definida para uma instância de um objeto.
    Data:       0 entries
    Stack trace:
   em Xpand.Persistent.Base.General.Controllers.Actions.ActionsClientScriptController.Frame_ProcessActionContainer(Object sender, ProcessActionContainerEventArgs e)
   em System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   em DevExpress.ExpressApp.Frame.OnProcessActionContainer(IActionContainer actionContainer)
   em DevExpress.ExpressApp.Frame.RaiseProcessActionContainerEvents(IEnumerable`1 actionContainers)
   em DevExpress.ExpressApp.Frame.SetTemplate(IFrameTemplate val)
   em DevExpress.ExpressApp.Web.WebWindow.CreateControls(Page page, Boolean checkRequestParams)
   em DevExpress.ExpressApp.Web.WebWindow.CreateControls(Page page)
   em DevExpress.ExpressApp.Web.WebApplication.CreateControlsCore(Page page)
   em DevExpress.ExpressApp.Web.WebApplication.CreateControls(Page page)
   em DevExpress.ExpressApp.Web.Templates.BaseXafPage.CreateControls()
   em DevExpress.ExpressApp.Web.Templates.BaseXafPage.OnInit(EventArgs e)
   em System.Web.UI.Control.InitRecursive(Control namingContainer)
   em System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
    InnerException is null

**Comment by Terricks** [comment]
I see you using Xpand,
XAFBootstrap has not been tested with Xpand, and there may occur a lot of errors

You can disable logon template - to do this you need to comment this part of code in Module.cs:
https://github.com/Terricks/XAFBootstrap/blob/master/15.1/Module.cs#L95-L96

**Comment by Stwart** [comment]
Thank's, i´ll give a try
