### ISSUE TITLE
Save button disappears

### ISSUE THREAD

**Issue by volkanalkilic** [Terricks/XAFBootstrap#13]
Hello,
in some cases, the Save, Save&New and other buttons disappears.

![image](https://cloud.githubusercontent.com/assets/14903319/10662167/41dc94e6-78bb-11e5-87e8-170a97326f87.png)

**Comment by Terricks** [comment]
Hi,
It's hard to say something by this screenshoot. If you attach sample app, that demonstrates problem - it will help to detect bug.

**Comment by volkanalkilic** [comment]
Project and a video describing the problem is in the following link;

https://www.wetransfer.com/downloads/9d51401b05f77f013f4265761629eaf820151022125240/a66ea0415e5f96b5fbe0fab122df3c3d20151022125240/5f9162

**Comment by Terricks** [comment]
In your archive two .exe files. You need to attach sources of your project (or demo project), where problem exists.

**Comment by volkanalkilic** [comment]
Yes, just run exe files and extract wherever you want.
Compressed files, I created with 7z.

**Comment by volkanalkilic** [comment]
Hello,
Is there any news?

**Comment by volkanalkilic** [comment]
Hello,
Is there any solution for this?

**Comment by Terricks** [comment]
There is no result on researching your problem. It needs more time and resources to discover. You can try to research it by yourself, because it seems to be not a regular bug. It may depend on your actions or custom controller logic.

**Comment by Terricks** [comment]
Could not repeat an issue.
