### ISSUE TITLE
Wrong row!

### ISSUE THREAD

**Issue by volkanalkilic** [Terricks/XAFBootstrap#15]
![image](https://cloud.githubusercontent.com/assets/14903319/10875841/974f6c00-813f-11e5-82eb-75f2002a8bb9.png)

**Comment by Terricks** [comment]
we found this issue too and fixed it (will appear in next update)
for now replace this part of code:
https://github.com/Terricks/XAFBootstrap/blob/master/15.1/Controls/XafBootstrapTable.cs#L900

to this:

<pre>var obj = objects.Skip(browseNum).FirstOrDefault();</pre>

**Comment by volkanalkilic** [comment]
I'm sorry to say this, but the problem was not solved!
Code not ever hit Handler_OnCallback

**Comment by volkanalkilic** [comment]
Note: the problem is occurring in the unsaved records

**Comment by volkanalkilic** [comment]
![image](https://cloud.githubusercontent.com/assets/14903319/10878700/2c472920-8158-11e5-81a0-002a8a1bc3c0.png)

**Comment by Terricks** [comment]
Enhanced in release 15.2
