### ISSUE TITLE
NullReferenceException after click a Random Page

### ISSUE THREAD

**Issue by claudiobertsch** [Terricks/XAFBootstrap#17]
Hello,
I have load the project and added it by your example on youtube...
All work fine, but when i click on a navigation item, i'm get a NullReferenceException. And i don't know where it comes from.. 

The error occurred:

```
Type:       NullReferenceException
Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Data:       0 entries
Stack trace:
```

Thats the last entries..

02.11.15 10:56:39.219   jny12l5zq1ufvbp1crzaaarl    Frame.set_Template: old value - null, new value - ASP.NestedFrameControl
02.11.15 10:56:39.255   jny12l5zq1ufvbp1crzaaarl    <-  WebWindow.CreateControls
02.11.15 10:56:39.388   jny12l5zq1ufvbp1crzaaarl    --------------------------------------------------------------------------------
02.11.15 10:56:39.389   jny12l5zq1ufvbp1crzaaarl    Execute action
02.11.15 10:56:39.389   jny12l5zq1ufvbp1crzaaarl        Type: DevExpress.ExpressApp.Actions.SingleChoiceAction
02.11.15 10:56:39.391   jny12l5zq1ufvbp1crzaaarl        ID: ShowNavigationItem
02.11.15 10:56:39.392   jny12l5zq1ufvbp1crzaaarl        Category: ViewsNavigation
02.11.15 10:56:39.392   jny12l5zq1ufvbp1crzaaarl        Controller.Name: DevExpress.ExpressApp.SystemModule.ShowNavigationItemController
02.11.15 10:56:39.393   jny12l5zq1ufvbp1crzaaarl        Context.Name: Startseite
02.11.15 10:56:39.394   jny12l5zq1ufvbp1crzaaarl        Context.IsRoot: True
02.11.15 10:56:39.395   jny12l5zq1ufvbp1crzaaarl        Context.SelectedObjects.Count: 0
02.11.15 10:56:39.396   jny12l5zq1ufvbp1crzaaarl        Context.CurrentObject: 
02.11.15 10:56:39.396   jny12l5zq1ufvbp1crzaaarl        SelectedItem: Anhaltende Datenelement Prüfung
02.11.15 10:56:39.398   jny12l5zq1ufvbp1crzaaarl    Creating the 'AuditDataItemPersistent_ListView' list view
02.11.15 10:56:39.400   jny12l5zq1ufvbp1crzaaarl    The 'AuditDataItemPersistent_ListView' list view is created
02.11.15 10:56:40.012   jny12l5zq1ufvbp1crzaaarl    Action 'ShowNavigationItem' done
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    CallbackManager_CallbackCompleted: 
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl        callbackManager: DevExpress.ExpressApp.Web.Templates.XafCallbackManager
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl        isLocked: False
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    -> RaisePagePreRender
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    <- RaisePagePreRender
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    startUpScripts were registered
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    clientScripts were registered
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    clientIncludeScripts were registered
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    clientScriptResources were registered
02.11.15 10:56:40.019   jny12l5zq1ufvbp1crzaaarl    CallbackManager_CallbackCompleted is completed

Did you have any idea?

**Comment by claudiobertsch** [comment]
![unbenannt2](https://cloud.githubusercontent.com/assets/15527154/10888868/cf344b78-818e-11e5-8713-8d9a737f7e87.PNG)

**Comment by Terricks** [comment]
Hi,
It's hard to say what really happens. Can you attach sample app that demonstrates problem?

**Comment by claudiobertsch** [comment]
Sorry i can't,... i try it with some demo applications, but there it isn't.. And i don't like to publish my project here. Is it possible to get a teamviewer session or something else?

**Comment by Terricks** [comment]
You can create new project and implement sample business object, that demonstrates problem. We must reproduce error to fix it.
Error appears when you click on any navigation item or just specific?

**Comment by claudiobertsch** [comment]
The problem is away when i change the defaultnavitem.
There was a dashboard with 2 listviews and 1 scheduler. when i close the dashboard the error comes.. now i have delete the dashboard and don't get the error any more..

so i think the problem is the dashboard with scheduler... a dashboard just with listviews don't produce the fail...

i will try a little bit and come back...

**Comment by Terricks** [comment]
Thank you for your researches, i'm sure it will be helpful to locate a bug

**Comment by claudiobertsch** [comment]
When i use any Page with the sheduler, the error come when i leave the specified Page. Do you have any Solution Idea?

**Comment by Terricks** [comment]
Try to disable XafBootstrap.Web.CustomDashboardViewRootController
