### ISSUE TITLE
LocalizedText

### ISSUE THREAD

**Issue by claudiobertsch** [Terricks/XAFBootstrap#18]
Please Complete the LocalizedText Items...
In Screenshot you find Some...

![unbenannt](https://cloud.githubusercontent.com/assets/15527154/10882636/ba783a7c-816c-11e5-84d7-6172edcdace7.PNG)

**Comment by Terricks** [comment]
Will be added

**Comment by claudiobertsch** [comment]
Thanks!!! Very fine!

**Comment by Terricks** [comment]
Enhanced in release 15.2
