### ISSUE TITLE
XafDefaultProperty only loads with this change in XafBootstrapTable.cs on line 257-259

### ISSUE THREAD

**Issue by claudiobertsch** [Terricks/XAFBootstrap#19]
![unbenannt](https://cloud.githubusercontent.com/assets/15527154/10912276/0372abd6-8249-11e5-8132-95cc9a417afd.PNG)

**Comment by Terricks** [comment]
Thank you, will be fixed next update

**Comment by Terricks** [comment]
Enhanced in release 15.2
