### ISSUE TITLE
Publishing app on IIS gives error message

### ISSUE THREAD

**Issue by MBrekhof** [Terricks/XAFBootstrap#2]
Not sure if it is related to this project or something else: solution runs fine from visual studio, after publishing to a (remote) IIS server I get an error message that The file '..../LogonTemplate.ascx' does not exist.

see image
![bootstrap](https://cloud.githubusercontent.com/assets/13586354/9005311/6c6e05c0-377d-11e5-86a6-ea79e0de93ff.PNG)

**Comment by Terricks** [comment]
You need to run DBUpdater tool (if you use it) - it will create all necessary files. Or you can include them to your web project manually (it creates in debug mode in.web folder automatically). Also, you can just copy them to your web published project.
.Web\bootstrap_css\*
.Web\bootstrap_js\*
.Web\bootstrap_themes\*
.Web\ContentTemplate.ascx
.Web\DialogTemplate.ascx
.Web\LogonTemplate.ascx
.Web\NestedFrameControl.ascx
.Web\XafBootstrapView.ascx
.Web\bin\Templates\*.ascx

**Comment by MBrekhof** [comment]
This solved it
