### ISSUE TITLE
use only on certain views 

### ISSUE THREAD

**Issue by volkanalkilic** [Terricks/XAFBootstrap#22]
Hello,

Is it possible to use XAFBootstrap only on certain views (pages)?

**Comment by Terricks** [comment]
Hi,
1) You can disable templates (Logon, Content, Dailog and Nested templates registering in Module.cs of Xaf Bootstrap) - and XAF will use standart templates .
2) For list views you can specify standart XAF list editors in Model.config
3) You can deactivate XafBootstrapDetailViewRootController for detail views where you need to show standart XAF layout.
4) For specific view items in detail view you can also specify standart XAF property editors in Model.config
5) Also as detail view you can deactivate dashboard views in XafBootstrapDashboardViewRootController.
