### ISSUE TITLE
Problem launch solution after add xafBootstrap Module (ActionConfirmUnsavedChangesController)

### ISSUE THREAD

**Issue by aitlahmid** [Terricks/XAFBootstrap#23]
Hi

Thank you for sharing this right module
I followed literally the installation steps. But, when i launch the solution, I get the following error:

The error occurred:

```
Type:       NullReferenceException
Message:    La référence d'objet n'est pas définie à une instance d'un objet.
Data:       0 entries
Stack trace:
```

   à DevExpress.ExpressApp.Web.SystemModule.ActionConfirmUnsavedChangesController.OnProcessActionContainer(WebActionContainer webActionContainer)
   à DevExpress.ExpressApp.Web.SystemModule.ProcessActionContainerHolderController.Frame_ProcessActionContainer(Object sender, ProcessActionContainerEventArgs e)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à DevExpress.ExpressApp.Frame.OnProcessActionContainer(IActionContainer actionContainer)
   à DevExpress.ExpressApp.Frame.RaiseProcessActionContainerEvents(IEnumerable`1 actionContainers)
   à DevExpress.ExpressApp.Frame.SetTemplate(IFrameTemplate val)
   à DevExpress.ExpressApp.Web.WebWindow.CreateControls(Page page, Boolean checkRequestParams)
   à DevExpress.ExpressApp.Web.WebWindow.CreateControls(Page page)
   à DevExpress.ExpressApp.Web.WebApplication.CreateControlsCore(Page page)
   à DevExpress.ExpressApp.Web.WebApplication.CreateControls(Page page)
   à DevExpress.ExpressApp.Web.Templates.BaseXafPage.CreateControls()
   à DevExpress.ExpressApp.Web.Templates.BaseXafPage.OnInit(EventArgs e)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
    InnerException is null

Thank you for your help

**Comment by Terricks** [comment]
Hi, thank you for feedback.
This problem solved in newer version of this module, but we haven't released it yet.
To solve this problem you must create controller and disable UnsavedChangesController that was made by DevExpress for new design.

```
    protected override void OnActivated()
    {
        base.OnActivated();           

        var focusController = Frame.GetController<DevExpress.ExpressApp.Web.SystemModule.FocusController>();
        if (focusController != null)
            focusController.Active["XafBootstrapActive"] = false;

        var unsavedDataController = Frame.GetController<DevExpress.ExpressApp.Web.SystemModule.ActionConfirmUnsavedChangesController>();
        if (unsavedDataController != null)
            unsavedDataController.Active["XafBootstrapActive"] = false;
    }
```

**Comment by aitlahmid** [comment]
Thank you

**Comment by aitlahmid** [comment]
No, another problem
i can't choose another theme. The action to change theme is disabled.
thanks.

**Comment by Terricks** [comment]
It's hard to say anything without any screen and working project, that demonstrates problem by steps. It have to work fine, so it looks like you need to research this problem by your own.
