### ISSUE TITLE
Problem Launch Application version 15.2

### ISSUE THREAD

**Issue by aitlahmid** [Terricks/XAFBootstrap#25]
Hi

When i launch the application i get the NullReferenceException . The log is:

   **à XAF_Bootstrap.Controls.XafBootstrapStringEdit.InnerRender() dans D:\INFO CL\INFOCL 2016\iclRegie - BS\XAF Bootstrap\Controls\XafBootstrapStringEdit.cs:ligne 77
   à XAF_Bootstrap.Controls.XafBootstrapStringEdit.set_Value(String value) dans D:\INFO CL\INFOCL 2016\iclRegie - BS\XAF Bootstrap\Controls\XafBootstrapStringEdit.cs:ligne 59
   à XAF_Bootstrap.Editors.XafBootstrapPropertyEditors.XafBootstrapStringPropertyEditor.ReadEditModeValueCore() dans D:\INFO CL\INFOCL 2016\iclRegie - BS\XAF Bootstrap\Editors\XafBootstrapPropertyEditors\XafBootstrapStringPropertyEditor.cs:ligne 76
   à DevExpress.ExpressApp.Web.Editors.WebPropertyEditor.ReadValueCore()
   à DevExpress.ExpressApp.Editors.PropertyEditor.ReadValue()
   à DevExpress.ExpressApp.Web.Editors.WebPropertyEditor.control_Init(Object sender, EventArgs e)
   à System.Web.UI.Control.OnInit(EventArgs e)
   à DevExpress.Web.ASPxWebControlBase.OnInit(EventArgs e)
   à XAF_Bootstrap.Controls.XafBootstrapStringEdit.OnInit(EventArgs e) dans D:\INFO CL\INFOCL 2016\iclRegie - BS\XAF Bootstrap\Controls\XafBootstrapStringEdit.cs:ligne 110
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.InitRecursive(Control namingContainer)
   à System.Web.UI.Control.AddedControl(Control control, Int32 index)
   à System.Web.UI.ControlCollection.Add(Control child)
   à DevExpress.ExpressApp.Web.Layout.LayoutItemTemplate.InstantiateInCore(LayoutItemTemplateContainerBase container)
   à DevExpress.ExpressApp.Web.Layout.LayoutBaseTemplate.InstantiateInCallback(LayoutItemTemplateContainerBase container)
   à DevExpress.ExpressApp.Web.Layout.DelayedControlInstantiationStrategy.<>c__DisplayClass2.<InstantiateIn>b__0(Object sender, EventArgs e)
   à System.EventHandler.Invoke(Object sender, EventArgs e)
   à System.Web.UI.Control.OnLoad(EventArgs e)
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Control.LoadRecursive()
   à System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)**

Thank you.

**Comment by Terricks** [comment]
Hi,
https://github.com/Terricks/XAFBootstrap/commit/f937211bee93509cd20c6e05e241fc0cf7944c94

It must help to resolve your problem.

**Comment by aitlahmid** [comment]
Thank you
