### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by boualemabid** [Terricks/XAFBootstrap#31]
Hi 
I receive an error when adding xaf bootstrap to my web solution

An exception of type 'System.NotSupportedException' occurred in DevExpress.Xpo.v15.2.dll but was not handled in user code

regards.

**Comment by Terricks** [comment]
Hi,
It's hard to say where problem is without stack trace and sample project, that demonstrates problem.
Do you have same troubles using default empty XAF project with XAF Bootstrap module?

**Comment by boualemabid** [comment]
Hi,
Thanks for your update,
bellow the error when removing all Navigation item and keep only Reports and defaults
"Exception occurs while assigning the 'ListView, ID:Analysis_ListView' view to WebWindow: 
Specified method is not supported."

**Comment by Terricks** [comment]
Unfortunately without any sample and stack trace we cannot say anything concrete. You can try to change list view editor in model for Analysis ListView back to default DevExpress table list editor, maybe it helps if problem in XAFBootstrap table editor.

**Comment by boualemabid** [comment]
Hi,

I solve the initial issue by recreating the solution. and it's working fine now. i need your help to change the font used to use RTL with ALmohand font.

regards.

**Comment by Terricks** [comment]
I'm glad to hear that you solved a problem.
We do not using in practice RTL, so you have to implement it by your own.
It's a web solution, so, for example, you can change font by adding custom css in Default.aspx.
