### ISSUE TITLE
Problem with XafDefaultProperty

### ISSUE THREAD

**Issue by angelSwp** [Terricks/XAFBootstrap#4]
Hi,
I am made a test project with the bootstrap, but I found a problem, the XafDefaultProperty in listView be presenting how the image down

![property](https://cloud.githubusercontent.com/assets/13755005/9210527/2dece558-4053-11e5-9656-c624bad15bab.PNG)

**Comment by Terricks** [comment]
Hi,
Try to use ObjectCaptionFormat attribute, like ObjectCaptionFormat("{0:Name}").

**Comment by Terricks** [comment]
Added support for XafDefaultProperty. If ObjectCaptionFormat
attribute has not been set - it uses XafDefaultProperty instead.

**Comment by claudiobertsch** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/15527154/10912150/68c0ae4e-8248-11e5-90b6-5ded37ff44e1.PNG)

![unbenannt2](https://cloud.githubusercontent.com/assets/15527154/10912155/6ca25896-8248-11e5-85aa-4254d7fb8c6d.PNG)

I think you have to change some rows in XAFBootstrapTable.cs on row 259.
the XafDefaultProperty don't work in my solution before i make the change in Pic 2
