### ISSUE TITLE
XafBootstrapLookupPropertyEditor problem

### ISSUE THREAD

**Issue by MBrekhof** [Terricks/XAFBootstrap#5]
Tried it with 15.1.5, works great after adapting XafBootstrapLookupPropertyEditor.cs: line 78 gives a problem, changed it to 
if (cs.List != null) 
IsSelector = cs.List.Count > 20 || cs.List.Count == 0; 
else 
IsSelector = true;

**Comment by Terricks** [comment]
Fixed
