### ISSUE TITLE
Color chooser request

### ISSUE THREAD

**Issue by MBrekhof** [Terricks/XAFBootstrap#6]
I have a property that is defined as:
        [Persistent("Kleur")]
        private Int32 _Kleur;
        [NonPersistent]
        public Color Kleur
        {
            get { return Color.FromArgb(_Kleur); }
            set
            {
                _Kleur = value.ToArgb();
                OnChanged("Kleur");
            }
        }

in kleur_old_listview (the first image) you can see how standard XAF displays the field in a listview, in kleur_listview the way it is displayed now. I would prefer the old one, is that possible?

![kleur_old_listview](https://cloud.githubusercontent.com/assets/13586354/9436533/668fa4d4-4a50-11e5-825b-51617082baf1.PNG)
![kleur_listview](https://cloud.githubusercontent.com/assets/13586354/9436537/6e30cbdc-4a50-11e5-9d65-73b06d7cdb09.PNG)

**Comment by Terricks** [comment]
![1](https://cloud.githubusercontent.com/assets/12909087/9437449/3471b1f4-4a78-11e5-91cd-0e690c08f689.png)
Will be available in next sources sync.

**Comment by Terricks** [comment]
Done

**Comment by MBrekhof** [comment]
thnx
